version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/" # Location of package manifests
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
      assignees:
        - "santoshmahto7"

    - package-ecosystem: "cargo"
      directory: "/" # Location of package manifests
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 20
      assignees:
        - "santoshmahto7"
